services:
  - type: web
    name: movie-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn movie_project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: movie_project.settings
      - key: SECRET_KEY
        generateValue: true
