services:
  - type: web
    name: movie-recommendation
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn movie_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: movie_project.settings
      - key: PYTHON_VERSION
        value: 3.11
